# Generated by Django 2.1.15 on 2020-04-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200418_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
