# Generated by Django 2.1.15 on 2020-04-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_employeerole_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.Team'),
            preserve_default=False,
        ),
    ]
